### ISSUE TITLE
Can I use autodiff reverse mode with Eigen::Tensor?

### ISSUE THREAD

**Issue by uvilla** [autodiff/autodiff#110] opened 2020-03-11 15:30 UTC
Dear developers,

Thank you very much for providing this very nice tool. 
I could not agree more with you with the statement `automatic differentiation in C++ could not be simpler`.

I am interested in using `autodiff` with `Eigen::Tensor` rather than `Eigen::Matrix`.
This worked well using the forward differentiation mode.

However, I am observing a very strange behavior when I run the code in reverse mode.
I rewritten  `example-reverse-gradient-derivatives-using-eigen.cpp` using `Eigen::Tensor<autodiff::var, 1>` rather then `autodiff::VectorXvar`:

```
// C++ includes
#include <iostream>

// Eigen includes
#include <Eigen/Core>
#include <Eigen/Dense>
#include <unsupported/Eigen/CXX11/Tensor>


// autodiff include
#include <autodiff/reverse.hpp>
#include <autodiff/reverse/eigen.hpp>

template<typename VALUE>
VALUE eval(const Eigen::Tensor<VALUE, 1> & x)
{

	Eigen::Tensor<VALUE, 0> y = (x*x).sum();

	return y(0);
}

int main()
{

	int n = 4;

	//Do everything using double
	{
		Eigen::Tensor<double, 1> x(n);
		x.setConstant(1.);

		double y = eval(x);

		std::cout<<"Using double\n";
		std::cout << "F(x) = "<< y <<"\n";

		std::cout << "dF/dx = ";
		double eps = 1.e-8;
		for(int i = 0; i < n; ++i)
		{
			x[i] += eps;
			double yplus = eval(x);
			std::cout << (yplus - y)/eps << " ";
			x[i] -= eps;
		}
		std::cout << std::endl;
	}

	//Do it again using autodiff::var
	Eigen::Tensor<autodiff::var, 1> x(n);
	x.setConstant(1.);
  
	autodiff::var y = eval(x);
	Eigen::RowVectorXd dydx =autodiff::gradient(y, x);

	
	std::cout<<"Use autodiff forward\n";
	std::cout << "F(u,p,m) = "<< y <<"\n";
	std::cout << "dF/dx = " << dydx <<"\n";
	return 0;
}
```

However, I'm getting a very unexpected result:

```
Using double
F(x) = 4
dF/dx = 2 2 2 2 
Use autodiff forward
F(u,p,m) = 4
dF/dx = 8 8 8 8
```

Do you have any insight on what could be the cause of this strange behavior?

Thank you in advance,

Umberto

**Comment by allanleal** [comment] 2020-03-11 19:18
Hi Umberto. Thanks for the feedback. I investigated the issue, and I found that the same `var` number is used in every component of the tensor, instead of distinct ones. By doing this:

~~~c++
Eigen::Tensor<autodiff::var, 1> x(n);
x(0) = autodiff::var(1.0);
x(1) = autodiff::var(1.0);
x(2) = autodiff::var(1.0);
x(3) = autodiff::var(1.0);
// x.setConstant(1.);
~~~

I managed to get as output:

~~~text
Using double
F(x) = 4
dF/dx = 2 2 2 2 
Use autodiff forward
F(u,p,m) = 4
dF/dx = 2 2 2 2
~~~

Interesting, because using Eigen::Matrix or Eigen::Array with `autodiff::var` works. I wonder if there is any change one can make from `autodiff`'s side to get this fixed, but I have the impression it might be related to Eigen::Tensor (but I can't check this now). If you discover more about this, please let me know.

**Comment by uvilla** [comment] 2020-03-12 03:34
Hi @allanleal ,

Thank you for your prompt reply. 
I now see the issue with `setConstant`:
- `autodiff::forward::dual` internally stores two doubles so the default copy constructor does the right job.
- `autodiff::var` stores a `shared_ptr<Expr>` so the default copy constructor simply create an new `autodiff::var` which points to the same `Expr` as the original one.

I don't know if the solution could be as simple as adding a copy constructor for `autodiff::var`, or this will break `autodiff` in other places.

**Comment by allanleal** [comment] 2020-03-13 14:49
Hi @uvilla ,

I'm preparing a pull request with major improvements for the reverse algorithm. It will be faster and fix this issue.

To resolve this use case you present, it will be necessary to remove implicit conversion from `double` to `var`, and you'll need to write:

~~~
tensor.setConstant(autodiff::constvar(1.0));  // or autodiff::constant, not sure the name yet
~~~

**Comment by uvilla** [comment] 2020-03-13 19:21
Thank you very much!

is #89 the PR you are referring to?

Another thing that I noted about `Eigen::Tensor` is that some of its methods allocate memory as a `char*` and then use `dynamic_cast<ScalarType *>` to convert them to the correct object.

Can the `autodiff::var` class be made safe w.r.t. respect to this way of allocating memory?
(`autodiff::forward::dual` behaves safely in this regard.)

**Comment by allanleal** [comment] 2020-03-16 17:28
Hi @uvilla - The PR I mentioned is #111 which I have just merged and fixes the error you were having. You should be able to get your original cpp file compiling and executing correctly now, without any modification. Let's see if this also fixes the other issue you are mentioning above. If not, could you please post a minimal reproducible example (in a new issue)?

**Closed by allanleal** 2020-03-16 17:28 UTC
