### ISSUE TITLE
Potential bug when using a unary minus

### ISSUE THREAD

**Issue by ludkinm** [autodiff/autodiff#41] opened 2019-07-03 10:50 UTC
I've spotted the following bug when using the dual type in ``forward.hpp``
```c++
dual f_bug(dual x)
{
  return -x - 2.0 * log(1.0 + exp(-x));
}
```
Running ``f(1.0)`` should result in ``-1.62652...`` however I get ``-1.0``

Adding parentheses fixes the problem:
```c++
dual f_ok(dual x)
{
  return -(x + 2.0 * log(1.0 + exp(-x)));
}
```
Is there an issue with the order of operations? Or is this expected behaviour?

**Comment by allanleal** [comment] 2019-07-03 11:13
I'm checking here.

**Comment by allanleal** [comment] 2019-07-03 13:04
Yes, I can confirm there is a bug - a difficult one to explain, since it is very subtle and it involves local variables (`BinaryExpr<L,R>`) being taken as reference inside an outer expression node (`NegExpr<BinaryExpr<L,R>&>` instead of `NegExpr<BinaryExpr<L,R>>`) because I was relying on automatic return type deduction in some places! A fix is on the way.

**Comment by allanleal** [comment] 2019-07-03 13:44
Just waiting for CI to pass to create a new release. Thanks for reporting this!

**Comment by ludkinm** [comment] 2019-07-03 14:12
No problem, thanks for the fix.

**Comment by allanleal** [comment] 2019-07-03 14:51
Fixed on release v0.5.5.

**Closed by allanleal** 2019-07-03 14:51 UTC
